### Scan API Endpoints

## Create a new scan

POST http://localhost:4000/api/v1/scan
Content-Type: application/json

{
    "repoUrl": "https://github.com/OWASP/NodeGoat"
}


### Get scan status by ID
GET http://localhost:4000/api/v1/scan/e70c4f5c-76a9-4273-99c5-abf42b422eed



