### Scan API Endpoints

## Create a new scan

POST http://localhost:4000/api/v1/scan
Content-Type: application/json

{
    "repoUrl": "https://github.com/OWASP/NodeGoat"
}


### Get scan status by ID
GET http://localhost:4000/api/v1/scan/b6cc87b9-495d-4dae-97ab-0ce1b786cdc0



