### Scan API Endpoints

## Create a new scan

POST http://localhost:4000/api/v1/scan
Content-Type: application/json

{
    "repoUrl": "https://github.com/OWASP/NodeGoat"
}


### Get scan status by ID
GET http://localhost:4000/api/v1/scan/627a2c59-52cc-48f0-9454-97afb837fdd2



