apiVersion: v1
kind: Service
metadata:
  name: nodegoat-app
  namespace: nodegoat-staging
spec:
  type: ClusterIP
  selector:
    app: nodegoat
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
